"""Matrix sweep launcher: generate per-cell configs, run the grid, resume pending.

The grid is ``datasets x models x optimizers x 8 learning rates x 5 seeds``.

* ``--init``    write any missing ``experiments/<dataset>_<model>_<optimizer>.yaml``
                cell config. Existing files are left untouched.
* ``--status``  print a done/pending table. A run is done iff its
                ``reports/<run_name>/summary.json`` exists: train.py writes that
                file last, so its presence marks a fully completed run.
* (default)     run every pending grid point as an isolated subprocess, skipping
                the ones already done. Idempotent: re-run it to resume.

Learning rate and seed are NOT stored in the cell YAMLs; they are injected per
run via ``--lr``/``--seed``. The run name is fully determined by
(model, dataset, optimizer, lr, seed), so the launcher predicts each output
directory and checks it without external bookkeeping.

Examples::

    python src/run_matrix.py --init            # write the cell configs
    python src/run_matrix.py --status          # done/pending table
    python src/run_matrix.py                   # run all pending runs (resume)
    python src/run_matrix.py --dataset mnist   # restrict to one dataset
    python src/run_matrix.py --dry-run         # print what would run, run nothing
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import time
from dataclasses import dataclass
from pathlib import Path

import yaml

from config import (
    DATASET_BUDGET,
    DATASETS,
    FIXED_KNOBS,
    LR_GRID,
    MODELS,
    OPTIMIZERS,
    ROOT,
    SEEDS,
    THRESHOLD_ACC,
)

EXPERIMENTS_DIR = ROOT / "experiments"
REPORTS_DIR = ROOT / "reports"
TRAIN_SCRIPT = Path(__file__).parent / "train.py"


def cell_path(dataset: str, model: str, optimizer: str) -> Path:
    """Path of the YAML config for one (dataset, model, optimizer) cell."""
    return EXPERIMENTS_DIR / f"{dataset}_{model}_{optimizer}.yaml"


def run_name_for(dataset: str, model: str, optimizer: str, lr: float, seed: int) -> str:
    """Must match ``train.default_run_name``."""
    return f"{model}_{dataset}_{optimizer}_lr{lr}_seed{seed}"


@dataclass(frozen=True)
class Run:
    """One grid point. Its identity fully determines its output directory."""

    dataset: str
    model: str
    optimizer: str
    lr: float
    seed: int

    @property
    def name(self) -> str:
        return run_name_for(self.dataset, self.model, self.optimizer, self.lr, self.seed)

    @property
    def config(self) -> Path:
        return cell_path(self.dataset, self.model, self.optimizer)

    def is_done(self) -> bool:
        """True iff a completed run already wrote its summary.json."""
        return (REPORTS_DIR / self.name / "summary.json").exists()


def enumerate_runs(
    datasets=DATASETS, models=MODELS, optimizers=OPTIMIZERS
) -> list[Run]:
    """Expand the selected axes into the full list of grid points."""
    return [
        Run(d, m, o, lr, s)
        for d in datasets
        for m in models
        for o in optimizers
        for lr in LR_GRID[o]
        for s in SEEDS
    ]


def init_cells() -> list[Path]:
    """Write any missing cell YAMLs; return the paths actually written."""
    EXPERIMENTS_DIR.mkdir(exist_ok=True)
    written: list[Path] = []
    for d in DATASETS:
        for m in MODELS:
            for o in OPTIMIZERS:
                path = cell_path(d, m, o)
                if path.exists():
                    continue
                knobs = {"dataset": d, "model": m, "optimizer": o,
                         **DATASET_BUDGET[d], "threshold_acc": THRESHOLD_ACC[(d, m)],
                         **FIXED_KNOBS}
                header = (
                    f"# Matrix cell: {d} x {m} x {o}.\n"
                    "# Generated by `python src/run_matrix.py --init`.\n"
                    "# Edit the budget here if a pilot says so; lr and seed are the\n"
                    "# sweep axes and are injected by the launcher -- do NOT pin them.\n"
                )
                path.write_text(header + yaml.safe_dump(knobs, sort_keys=False))
                written.append(path)
    return written


def build_command(run: Run) -> list[str]:
    """The subprocess argv that trains exactly one grid point."""
    return [
        sys.executable, str(TRAIN_SCRIPT),
        "--config", str(run.config),
        "--lr", str(run.lr),
        "--seed", str(run.seed),
        "--run-name", run.name,
        "--out-dir", str(REPORTS_DIR),  # absolute -> cwd-independent
    ]


def child_env() -> dict[str, str]:
    """Environment copy; ``PYTORCH_CUDA_ALLOC_CONF`` is defaulted, a set value wins."""
    env = dict(os.environ)
    env.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")
    return env


def print_status(runs: list[Run]) -> None:
    """Print per-cell and overall done/total counts."""
    cells: dict[tuple[str, str, str], list[Run]] = {}
    for r in runs:
        cells.setdefault((r.dataset, r.model, r.optimizer), []).append(r)

    print("[run_matrix] done / total per cell\n")
    total_done = 0
    for (d, m, o), cell_runs in cells.items():
        done = sum(r.is_done() for r in cell_runs)
        total_done += done
        flag = "" if done == len(cell_runs) else "  <- pending"
        print(f"  {d:<14} {m:<9} {o:<5} {done:>2}/{len(cell_runs)}{flag}")

    pct = 100.0 * total_done / len(runs) if runs else 0.0
    print(f"\n  TOTAL {total_done}/{len(runs)}  ({pct:.1f}% complete)")


def fmt_duration(seconds: float) -> str:
    """Wall-clock as one short human-readable token: ``45s``, ``2.4m``, ``1h07m``."""
    if seconds < 60:
        return f"{seconds:.0f}s"
    if seconds < 3600:
        return f"{seconds / 60:.1f}m"
    return f"{seconds // 3600:.0f}h{(seconds % 3600) / 60:02.0f}m"


def execute(
    runs: list,
    dry_run: bool = False,
    limit: int | None = None,
    build=build_command,
    label: str = "run_matrix",
) -> list:
    """Run every pending job sequentially; return the ones that failed.

    Drives anything with ``is_done()``, ``name`` and ``config``, so the pilot
    launcher reuses it by passing its own ``build`` and ``label``.
    """
    done = [r for r in runs if r.is_done()]
    pending = [r for r in runs if not r.is_done()]
    selected = pending if limit is None else pending[:limit]

    missing = sorted({r.config for r in selected if not r.config.exists()})
    if missing:
        print(f"[{label}] missing cell configs -- run `run_matrix.py --init` first:")
        for c in missing:
            print(f"    {c.relative_to(ROOT)}")
        return selected

    note = "" if limit is None else f" (capped from {len(pending)} pending)"
    print(f"[{label}] {len(done)} done, {len(selected)} to run{note} "
          f"(of {len(runs)} selected)")
    failures: list = []
    batch_started = time.monotonic()
    for i, run in enumerate(selected, 1):
        cmd = build(run)
        if dry_run:
            print("  DRY  " + " ".join(cmd))
            continue
        print(f"\n[{label}] ({i}/{len(selected)}) {run.name}")
        run_started = time.monotonic()
        failed = subprocess.run(cmd, env=child_env()).returncode != 0
        run_elapsed = time.monotonic() - run_started
        if failed:
            print(f"[{label}] FAILED: {run.name} (left pending)")
            failures.append(run)
        print(f"[{label}] {fmt_duration(run_elapsed)} this run | "
              f"{fmt_duration(time.monotonic() - batch_started)} elapsed, "
              f"{i}/{len(selected)} of this batch")

    if not dry_run:
        ok = len(selected) - len(failures)
        print(f"\n[{label}] finished: {ok} ok, {len(failures)} failed "
              f"in {fmt_duration(time.monotonic() - batch_started)}")
        for r in failures:
            print(f"    still pending: {r.name}")
    return failures


def main(argv: list[str] | None = None) -> None:
    p = argparse.ArgumentParser(
        description="Generate, track, and resume the experiment matrix.",
    )
    p.add_argument("--init", action="store_true",
                   help="write missing cell config YAMLs and exit")
    p.add_argument("--status", action="store_true",
                   help="print the done/pending table and exit")
    p.add_argument("--dry-run", action="store_true",
                   help="print the runs that would launch, run nothing")
    p.add_argument("--limit", type=int, default=None,
                   help="run at most N pending runs (useful for a smoke check)")
    p.add_argument("--dataset", choices=DATASETS, help="restrict to one dataset")
    p.add_argument("--model", choices=MODELS, help="restrict to one model")
    p.add_argument("--optimizer", choices=OPTIMIZERS, help="restrict to one optimizer")
    args = p.parse_args(argv)

    if args.init:
        written = init_cells()
        print(f"[run_matrix] wrote {len(written)} new cell config(s); "
              f"{len(DATASETS) * len(MODELS) * len(OPTIMIZERS) - len(written)} already present")
        for path in written:
            print(f"    {path.relative_to(ROOT)}")
        return

    runs = enumerate_runs(
        datasets=(args.dataset,) if args.dataset else DATASETS,
        models=(args.model,) if args.model else MODELS,
        optimizers=(args.optimizer,) if args.optimizer else OPTIMIZERS,
    )
    if args.status:
        print_status(runs)
        return
    execute(runs, dry_run=args.dry_run, limit=args.limit)


if __name__ == "__main__":
    main()
